# Generated by Django 3.1.1 on 2020-12-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_src', models.TextField(max_length=300)),
                ('item_value', models.CharField(max_length=30)),
                ('item_description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=11, unique=True)),
                ('wx', models.CharField(max_length=11, unique=True)),
                ('zfb', models.CharField(max_length=11, unique=True)),
                ('addr1', models.CharField(max_length=30)),
                ('addr2', models.CharField(max_length=30)),
            ],
        ),
    ]
