# Generated by Django 3.1.1 on 2020-12-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Itemsss',
        ),
    ]
