# Generated by Django 3.1.1 on 2021-02-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_itrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopcars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_no', models.IntegerField(null=True)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('item_id', models.IntegerField(null=True)),
                ('item_counter', models.IntegerField(null=True)),
                ('item_value', models.CharField(max_length=30)),
                ('item_money', models.CharField(max_length=30)),
            ],
        ),
    ]
